<?php $this->partial('shared/header'); ?>

<form method="post" class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="page-header">
                <div class="pull-right">
                    <a class="btn btn-default" href="<?= $ref ?>" type="button">Cancel</a>
                    <button class="btn btn-primary">Save</button>
                </div>
                <h3><?= $title ?></h3>
            </div>
        </div>
    </div>
    
    <div class="row">
        <div class="col-md-9">
            <div class="row">
                <?php $col = module_exists('post-canal') && $this->can_i->read_post_canal ? '8' : '12'; ?>
                <div class="col-md-<?= $col ?>">
                    <?= $this->form->field('name'); ?>
                </div>
                <?php if($col == 8): ?>
                    <div class="col-md-4">
                        <?= $this->form->field('canal', $canals); ?>
                    </div>
                <?php else: ?>
                    <input type="hidden" id="field-canal" value="<?= $object->canal ?? '0' ?>">
                <?php endif; ?>
            </div>
            <div class="row">
                <div class="col-md-8">
                    <?= $this->form->field('slug'); ?>
                    <?= $this->form->field('about'); ?>
                </div>
                <div class="col-md-4">
                    <?= $this->form->field('parent', $categories); ?>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <?= $this->form->field('meta_title'); ?>
                    <?= $this->form->field('meta_description'); ?>
                    <?= $this->form->field('meta_keywords'); ?>
                </div>
            </div>
        </div>
    </div>
</form>

<?php $this->partial('shared/footer'); ?>